Session.create(:id => 8294, :identifier => "animagrove", :sources => [], :saved_items => [])
Session.create(:id => 8295, :identifier => "daringsage", :sources => [], :saved_items => [])
Session.create(:id => 8296, :identifier => "trimbunny", :sources => [], :saved_items => [])
Session.create(:id => 6430, :identifier => "plumshark", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6896, :identifier => "hugetree", :sources => [], :completed_to => Mon, 30 Mar 2015 12:26:27 UTC +00:00, :saved_items => [])
Session.create(:id => 8297, :identifier => "wholetigers", :sources => [], :saved_items => [])
Session.create(:id => 8298, :identifier => "poeticocean", :sources => [], :saved_items => [])
Session.create(:id => 8299, :identifier => "newsnowflake", :sources => [], :saved_items => [])
Session.create(:id => 8300, :identifier => "indigospoon", :sources => [], :saved_items => [])
Session.create(:id => 6781, :identifier => "vestalcreek", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 3, :identifier => "coolball", :sources => [], :completed_to => Mon, 09 Mar 2015 20:57:38 UTC +00:00, :saved_items => [])
Session.create(:id => 8301, :identifier => "civilcavern", :sources => [], :saved_items => [])
Session.create(:id => 8302, :identifier => "upbeatsparrow", :sources => [], :saved_items => [])
Session.create(:id => 6338, :identifier => "heartyhouse", :sources => ["macrumors", "qudos"], :completed_to => Fri, 27 Mar 2015 15:16:34 UTC +00:00, :saved_items => [])
Session.create(:id => 8303, :identifier => "maxednature", :sources => [], :saved_items => [])
Session.create(:id => 8304, :identifier => "apple-touch-icon-120x120-precomposed", :sources => [], :saved_items => [])
Session.create(:id => 6339, :identifier => "loveddove", :sources => ["product_hunt", "reddit", "slashdot"], :saved_items => [])
Session.create(:id => 117, :identifier => "upliftingpants", :sources => ["hacker_news", "arstechnica"], :completed_to => Sat, 11 Apr 2015 20:06:56 UTC +00:00, :saved_items => [])
Session.create(:id => 7319, :identifier => "dryice", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 8305, :identifier => "apple-touch-icon-120x120", :sources => [], :saved_items => [])
Session.create(:id => 8306, :identifier => "apple-touch-icon", :sources => [], :saved_items => [])
Session.create(:id => 8307, :identifier => "apple-touch-icon-precomposed", :sources => [], :saved_items => [])
Session.create(:id => 6449, :identifier => "bosssage", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 12, :identifier => "deepflood", :sources => ["hacker_news"], :completed_to => Sun, 05 Apr 2015 17:56:35 UTC +00:00, :saved_items => [])
Session.create(:id => 6451, :identifier => "earthyfjord", :sources => ["hacker_news", "reddit", "arstechnica"], :saved_items => [])
Session.create(:id => 7324, :identifier => "lushspoon", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 8308, :identifier => "wingedbread", :sources => [], :saved_items => [])
Session.create(:id => 7326, :identifier => "modernaurora", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 14, :identifier => "maturesoil", :sources => [], :completed_to => Tue, 10 Mar 2015 13:46:39 UTC +00:00, :saved_items => [])
Session.create(:id => 7327, :identifier => "simpledew", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6357, :identifier => "unitedlawn", :sources => ["slashdot", "qudos"], :saved_items => [])
Session.create(:id => 6450, :identifier => "quiettundra", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 7328, :identifier => "serenetiger", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 7256, :identifier => "potenttruck", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6913, :identifier => "reachpond", :sources => ["hacker_news", "product_hunt", "reddit", "slashdot", "beta_list", "macrumors", "qudos", "designer_news", "arstechnica"], :saved_items => [])
Session.create(:id => 6361, :identifier => "rosybush", :sources => ["reddit", "qudos", "github", "arstechnica", "slashdot", "hacker_news"], :completed_to => Fri, 27 Mar 2015 18:36:34 UTC +00:00, :saved_items => [])
Session.create(:id => 6460, :identifier => "quietbacon", :sources => ["product_hunt", "hacker_news", "slashdot"], :saved_items => [])
Session.create(:id => 8309, :identifier => "sweetrabbit", :sources => [], :saved_items => [])
Session.create(:id => 7330, :identifier => "holyhug", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 8310, :identifier => "rootedguide", :sources => [], :saved_items => [])
Session.create(:id => 8311, :identifier => "ideallake", :sources => [], :saved_items => [])
Session.create(:id => 8312, :identifier => "sunsetdove", :sources => [], :saved_items => [])
Session.create(:id => 6467, :identifier => "celestiallagoon", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 8313, :identifier => "drivenmouse", :sources => [], :saved_items => [])
Session.create(:id => 8314, :identifier => "lawfulresonance", :sources => [], :saved_items => [])
Session.create(:id => 8315, :identifier => "amiablewaves", :sources => [], :saved_items => [])
Session.create(:id => 8316, :identifier => "vitalautumn", :sources => [], :saved_items => [])
Session.create(:id => 6445, :identifier => "wisesage", :sources => ["reddit", "hacker_news"], :completed_to => Sat, 28 Mar 2015 16:46:43 UTC +00:00, :saved_items => [])
Session.create(:id => 8317, :identifier => "hipsilence", :sources => [], :saved_items => [])
Session.create(:id => 8318, :identifier => "prizedwindow", :sources => [], :saved_items => [])
Session.create(:id => 8319, :identifier => "moonlitsummer", :sources => [], :saved_items => [])
Session.create(:id => 8320, :identifier => "quainthurricane", :sources => [], :saved_items => [])
Session.create(:id => 8321, :identifier => "likelyspoon", :sources => [], :saved_items => [])
Session.create(:id => 8322, :identifier => "lovelyguru", :sources => [], :saved_items => [])
Session.create(:id => 6922, :identifier => "ykorman", :sources => ["hacker_news", "product_hunt", "slashdot", "beta_list", "qudos", "designer_news", "arstechnica", "macrumors"], :saved_items => [])
Session.create(:id => 8323, :identifier => "superbpebble", :sources => [], :saved_items => [])
Session.create(:id => 8324, :identifier => "talenteddog", :sources => [], :saved_items => [])
Session.create(:id => 8325, :identifier => "fancyprize", :sources => [], :saved_items => [])
Session.create(:id => 8326, :identifier => "primotundra", :sources => [], :saved_items => [])
Session.create(:id => 6776, :identifier => "vogueice", :sources => [], :completed_to => Mon, 30 Mar 2015 02:16:31 UTC +00:00, :saved_items => [])
Session.create(:id => 8327, :identifier => "usefulcandy", :sources => [], :saved_items => [])
Session.create(:id => 8328, :identifier => "mightysoil", :sources => [], :saved_items => [])
Session.create(:id => 8329, :identifier => "unitedabyss", :sources => [], :saved_items => [])
Session.create(:id => 8330, :identifier => "okayapple", :sources => [], :saved_items => [])
Session.create(:id => 8331, :identifier => "luckyatoll", :sources => [], :saved_items => [])
Session.create(:id => 8332, :identifier => "billowingbear", :sources => [], :saved_items => [])
Session.create(:id => 8333, :identifier => "frightenedpebble", :sources => [], :saved_items => [])
Session.create(:id => 8334, :identifier => "naturalpine", :sources => [], :saved_items => [])
Session.create(:id => 8335, :identifier => "okaybadlands", :sources => [], :saved_items => [])
Session.create(:id => 8336, :identifier => "worthydog", :sources => [], :saved_items => [])
Session.create(:id => 8337, :identifier => "augustchasm", :sources => [], :saved_items => [])
Session.create(:id => 8338, :identifier => "mirthfulbook", :sources => [], :saved_items => [])
Session.create(:id => 8339, :identifier => "swiftmilk", :sources => [], :saved_items => [])
Session.create(:id => 8340, :identifier => "sunsetduck", :sources => [], :saved_items => [])
Session.create(:id => 8341, :identifier => "rapidbunny", :sources => [], :saved_items => [])
Session.create(:id => 8342, :identifier => "honestbriars", :sources => [], :saved_items => [])
Session.create(:id => 8343, :identifier => "stablecreek", :sources => [], :saved_items => [])
Session.create(:id => 8344, :identifier => "arechip", :sources => [], :saved_items => [])
Session.create(:id => 8345, :identifier => "condemnedpilot", :sources => [], :saved_items => [])
Session.create(:id => 8346, :identifier => "goldenpeak", :sources => [], :saved_items => [])
Session.create(:id => 8347, :identifier => "legitreserve", :sources => [], :saved_items => [])
Session.create(:id => 8348, :identifier => "plumbunny", :sources => [], :saved_items => [])
Session.create(:id => 6826, :identifier => "starkfjord", :sources => [], :completed_to => Sun, 29 Mar 2015 22:06:29 UTC +00:00, :saved_items => [])
Session.create(:id => 7259, :identifier => "wingedsurf", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 6110, :identifier => "wantedvalley", :sources => [], :completed_to => Thu, 19 Mar 2015 18:06:47 UTC +00:00, :saved_items => [])
Session.create(:id => 6366, :identifier => "parchedspring", :sources => [], :completed_to => Fri, 27 Mar 2015 19:46:31 UTC +00:00, :saved_items => [])
Session.create(:id => 6828, :identifier => "robustsalute", :sources => ["hacker_news"], :completed_to => Sun, 29 Mar 2015 23:06:31 UTC +00:00, :saved_items => [])
Session.create(:id => 6481, :identifier => "socialstreamkp", :sources => ["hacker_news", "product_hunt"], :completed_to => Sat, 28 Mar 2015 14:36:30 UTC +00:00, :saved_items => [])
Session.create(:id => 5680, :identifier => "lucidcar", :sources => ["github"], :saved_items => [])
Session.create(:id => 5681, :identifier => "exactplanet", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 5682, :identifier => "boldfreeze", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 5683, :identifier => "snazzybowl", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 5684, :identifier => "dapperatoll", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 5685, :identifier => "hunkyplane", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 5686, :identifier => "scenicsunset", :sources => [], :completed_to => Thu, 19 Mar 2015 22:46:41 UTC +00:00, :saved_items => [])
Session.create(:id => 5687, :identifier => "poeticcoal", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 5688, :identifier => "chummychip", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 5689, :identifier => "dotingbreeze", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 6490, :identifier => "spacialforest", :sources => [], :completed_to => Sat, 28 Mar 2015 14:56:21 UTC +00:00, :saved_items => [])
Session.create(:id => 6494, :identifier => "likedhill", :sources => [], :completed_to => Sat, 28 Mar 2015 15:06:32 UTC +00:00, :saved_items => [])
Session.create(:id => 6506, :identifier => "maxedbush", :sources => ["hacker_news", "reddit"], :saved_items => [])
Session.create(:id => 6512, :identifier => "novelcoal", :sources => [], :completed_to => Sat, 28 Mar 2015 15:36:49 UTC +00:00, :saved_items => [])
Session.create(:id => 6523, :identifier => "cuddlytemple", :sources => ["hacker_news", "arstechnica"], :saved_items => [])
Session.create(:id => 6942, :identifier => "uniquelight", :sources => ["hacker_news", "product_hunt"], :saved_items => [])
Session.create(:id => 8349, :identifier => "joyousswamp", :sources => [], :saved_items => [])
Session.create(:id => 8350, :identifier => "purringleaves", :sources => [], :saved_items => [])
Session.create(:id => 8351, :identifier => "chiefduck", :sources => [], :saved_items => [])
Session.create(:id => 8352, :identifier => "apple-touch-icon-152x152-precomposed", :sources => [], :saved_items => [])
Session.create(:id => 8353, :identifier => "apple-touch-icon-152x152", :sources => [], :saved_items => [])
Session.create(:id => 6531, :identifier => "givingprize", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6191, :identifier => "viablemoon", :sources => ["hacker_news", "product_hunt", "beta_list", "macrumors", "qudos", "designer_news"], :saved_items => [])
Session.create(:id => 8354, :identifier => "nobleplane", :sources => [], :saved_items => [])
Session.create(:id => 7208, :identifier => "fitbike", :sources => ["slashdot"], :saved_items => [])
Session.create(:id => 8355, :identifier => "richcow", :sources => [], :saved_items => [])
Session.create(:id => 2, :identifier => "immuneplant", :sources => ["lobsters"], :completed_to => Sun, 19 Apr 2015 08:16:35 UTC +00:00, :trello_token => "3fc757f82ec608b639ea40b8c1d7597a61ab47aa6b09267ac257877cf3f4453d", :trello_username => "charlieegan3", :saved_items => [7749, 7757, 7760, 7762, 7767, 7778, 7801, 7810, 7818, 7845, 7857, 7856, 7860, 7869, 7870, 7874, 7880, 7884, 7891, 7892, 7895, 7901, 7918, 7930, 7934, 7937, 7937, 7944, 7950, 7953, 7975, 7993, 7998, 8011, 8016, 8037, 8074, 8088, 8096, 8101, 8120, 8129, 8144, 8168, 8172, 8181, 8217, 8238, 8251, 8259, 8262, 8281, 8307, 8311, 8315, 8319, 8321, 8332, 8333, 8337, 8378, 8450, 8451, 8465, 8466, 8467, 8486, 8488, 8488, 8499, 8521, 8522, 8544, 8545, 8567, 8605, 8608, 8618, 8623, 8624, 8625, 8626, 8631, 8643, 8648, 8713, 8782, 8785, 8792, 8801, 8813, 8834, 8837, 8850, 8868, 8872, 8882, 8885, 8892, 8896, 8910, 8930, 8940, 8941, 8944, 8976, 8977, 8981, 8984, 9015, 9019, 9051, 9060, 9061, 9074, 9088, 9093, 9158, 9174, 9197, 9202, 9206, 9215, 9216, 9218, 9241, 9289, 9300, 9312, 9313, 9317, 9318, 9338, 9376, 9393, 9399, 9411, 9444, 9449, 9452, 9473, 9547, 9561, 9579, 9580, 9583, 9599, 9606, 9622, 9626, 9629, 9635, 9646, 9658, 9675, 9714, 9729, 9732, 9733, 9738, 9764, 9781, 9813, 9841, 9865, 9882, 9899, 9926, 9929, 9975, 9980, 9991, 9993, 9997, 10018, 10037, 10064, 10104, 10114, 10141, 10175, 10179, 10192, 10202, 10204, 10216, 10236, 10242, 10266, 10271, 10274, 10304, 10309, 10333, 10333, 10335, 10394, 10412, 10415, 10444, 10468, 10490, 10474, 10495, 10534, 10560, 10569, 10591, 10620, 10638, 10649, 10668, 10651, 10659, 10689, 10725, 10758, 10812, 10822, 10826, 10841, 10870, 10907, 10974, 11037, 11051, 11206, 11212, 11218, 11233, 11314, 11324, 11437, 11442, 11465, 11466, 11500, 11501, 11541, 11572, 11591, 11593, 11603, 11749, 11762, 11826, 11863, 11877, 11941, 11954, 11984, 11988, 11991, 11998, 12008, 12093, 12210, 12295, 12395, 12397, 12426, 12432])
Session.create(:id => 8356, :identifier => "dreamyfield", :sources => [], :saved_items => [])
Session.create(:id => 8357, :identifier => "superbbee", :sources => [], :saved_items => [])
Session.create(:id => 6410, :identifier => "composedgarden", :sources => ["reddit", "github"], :saved_items => [])
Session.create(:id => 6549, :identifier => "puresage", :sources => ["product_hunt", "hacker_news", "reddit", "designer_news"], :completed_to => Sat, 28 Mar 2015 17:36:44 UTC +00:00, :saved_items => [])
Session.create(:id => 6551, :identifier => "fancysummit", :sources => ["hacker_news", "slashdot"], :saved_items => [])
Session.create(:id => 6572, :identifier => "pluckysoup", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6574, :identifier => "deftplanet", :sources => ["qudos", "designer_news"], :saved_items => [])
Session.create(:id => 8358, :identifier => "purringbook", :sources => [], :saved_items => [])
Session.create(:id => 8359, :identifier => "primowaterfall", :sources => [], :saved_items => [])
Session.create(:id => 8360, :identifier => "peppymilk", :sources => [], :saved_items => [])
Session.create(:id => 8361, :identifier => "prolagoon", :sources => [], :saved_items => [])
Session.create(:id => 8362, :identifier => "amplefu", :sources => [], :saved_items => [])
Session.create(:id => 5589, :identifier => "astuteshoe", :sources => [], :completed_to => Thu, 19 Mar 2015 22:46:41 UTC +00:00, :saved_items => [])
Session.create(:id => 5590, :identifier => "poisedtiger", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 5591, :identifier => "divinecar", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 5592, :identifier => "justdesert", :sources => ["github"], :saved_items => [])
Session.create(:id => 5593, :identifier => "astuteforest", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 5594, :identifier => "dotingjuice", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 5595, :identifier => "showytowel", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 5596, :identifier => "astutegalaxy", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 5597, :identifier => "hollowdove", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 5598, :identifier => "mutualball", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 6604, :identifier => "swanktsunami", :sources => ["hacker_news", "reddit", "product_hunt", "beta_list", "slashdot", "macrumors", "qudos", "designer_news", "arstechnica"], :saved_items => [])
Session.create(:id => 6609, :identifier => "enigmaticduck", :sources => ["hacker_news", "slashdot", "beta_list"], :saved_items => [])
Session.create(:id => 6610, :identifier => "livelyrabbit", :sources => ["hacker_news", "reddit"], :saved_items => [])
Session.create(:id => 6635, :identifier => "endcavern", :sources => ["hacker_news", "product_hunt", "slashdot", "qudos"], :saved_items => [])
Session.create(:id => 6640, :identifier => "starksnowflake", :sources => [], :completed_to => Sat, 28 Mar 2015 22:36:22 UTC +00:00, :saved_items => [])
Session.create(:id => 8216, :identifier => "poisedsunrise", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 6647, :identifier => "richfrog", :sources => [], :completed_to => Sat, 28 Mar 2015 22:46:33 UTC +00:00, :saved_items => [])
Session.create(:id => 5619, :identifier => "goldoasis", :sources => ["github"], :saved_items => [])
Session.create(:id => 5620, :identifier => "likelystorm", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 5621, :identifier => "peppycrater", :sources => [], :completed_to => Thu, 19 Mar 2015 22:46:41 UTC +00:00, :saved_items => [])
Session.create(:id => 6662, :identifier => "adeptfall", :sources => ["hacker_news", "reddit", "slashdot", "arstechnica"], :saved_items => [])
Session.create(:id => 6692, :identifier => "indigotowel", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6691, :identifier => "alertreef", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 6695, :identifier => "hugebird", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 5622, :identifier => "endfog", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 5623, :identifier => "caringoasis", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 5624, :identifier => "guidedcliff", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 5625, :identifier => "uniquefall", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 5626, :identifier => "homelessprize", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 5627, :identifier => "fondtruck", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 5628, :identifier => "livelymoon", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 5636, :identifier => "voicelesspond", :sources => [], :completed_to => Fri, 20 Mar 2015 07:31:20 UTC +00:00, :saved_items => [])
Session.create(:id => 5647, :identifier => "prettyplane", :sources => ["github"], :saved_items => [])
Session.create(:id => 5648, :identifier => "worthynature", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 5649, :identifier => "earthywild", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 5650, :identifier => "divinenature", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 5651, :identifier => "exuberantmarsh", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 5652, :identifier => "overtsun", :sources => [], :completed_to => Thu, 19 Mar 2015 22:46:41 UTC +00:00, :saved_items => [])
Session.create(:id => 5653, :identifier => "condemnedtundra", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 5654, :identifier => "gracefulresonance", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 5655, :identifier => "cannyapple", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 5656, :identifier => "proudspring", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 6703, :identifier => "cogenttigers", :sources => ["arstechnica", "hacker_news", "product_hunt", "reddit", "beta_list", "macrumors", "designer_news", "qudos"], :saved_items => [])
Session.create(:id => 6706, :identifier => "lawfulforest", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 6712, :identifier => "screechingpeak", :sources => ["designer_news", "qudos", "hacker_news"], :saved_items => [])
Session.create(:id => 6714, :identifier => "stablejuice", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 6421, :identifier => "adroitdawn", :sources => [], :completed_to => Sat, 28 Mar 2015 11:46:31 UTC +00:00, :saved_items => [])
Session.create(:id => 6424, :identifier => "vestalwillow", :sources => [], :completed_to => Sat, 28 Mar 2015 11:46:31 UTC +00:00, :saved_items => [])
Session.create(:id => 6427, :identifier => "cuddlylawn", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6757, :identifier => "starklawn", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6758, :identifier => "mellowsky", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 6759, :identifier => "righthurricane", :sources => ["reddit"], :saved_items => [])
Session.create(:id => 6761, :identifier => "robustpeak", :sources => ["macrumors"], :saved_items => [])
Session.create(:id => 6762, :identifier => "aliveice", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 6763, :identifier => "chieffrog", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 6765, :identifier => "seemlydawn", :sources => ["arstechnica"], :saved_items => [])
Session.create(:id => 6766, :identifier => "unitedfarm", :sources => ["product_hunt"], :saved_items => [])
Session.create(:id => 6767, :identifier => "trimswamp", :sources => ["designer_news"], :saved_items => [])
Session.create(:id => 7854, :identifier => "deftnature", :sources => [], :completed_to => Sun, 12 Apr 2015 07:16:46 UTC +00:00, :saved_items => [])
Session.create(:id => 8264, :identifier => "earthyleaf", :sources => [], :saved_items => [])
Session.create(:id => 8265, :identifier => "frightenedstorm", :sources => [], :saved_items => [])
Session.create(:id => 8266, :identifier => "poeticcat", :sources => [], :saved_items => [])
Session.create(:id => 8267, :identifier => "unwaveringforest", :sources => [], :saved_items => [])
Session.create(:id => 8268, :identifier => "suresmokescreen", :sources => [], :saved_items => [])
Session.create(:id => 8269, :identifier => "sereneboat", :sources => [], :saved_items => [])
Session.create(:id => 8270, :identifier => "daringsoil", :sources => [], :saved_items => [])
Session.create(:id => 8271, :identifier => "apthat", :sources => [], :saved_items => [])
Session.create(:id => 8272, :identifier => "vividflood", :sources => [], :saved_items => [])
Session.create(:id => 8273, :identifier => "poetictree", :sources => [], :saved_items => [])
Session.create(:id => 8274, :identifier => "viableaurora", :sources => [], :saved_items => [])
Session.create(:id => 8275, :identifier => "tidyocean", :sources => [], :saved_items => [])
Session.create(:id => 8276, :identifier => "clearbook", :sources => [], :saved_items => [])
Session.create(:id => 8277, :identifier => "nativefield", :sources => [], :saved_items => [])
Session.create(:id => 8278, :identifier => "trustylagoon", :sources => [], :saved_items => [])
Session.create(:id => 8279, :identifier => "dapperapple", :sources => [], :saved_items => [])
Session.create(:id => 8280, :identifier => "usefultundra", :sources => [], :saved_items => [])
Session.create(:id => 8281, :identifier => "topdew", :sources => [], :saved_items => [])
Session.create(:id => 8282, :identifier => "topsrange", :sources => [], :saved_items => [])
Session.create(:id => 8283, :identifier => "starksparrow", :sources => [], :saved_items => [])
Session.create(:id => 8284, :identifier => "tidywinds", :sources => [], :saved_items => [])
Session.create(:id => 8285, :identifier => "bravehat", :sources => [], :saved_items => [])
Session.create(:id => 8286, :identifier => "seemlymilk", :sources => [], :saved_items => [])
Session.create(:id => 8287, :identifier => "mellowsky", :sources => [], :saved_items => [])
Session.create(:id => 8288, :identifier => "starkfern", :sources => [], :saved_items => [])
Session.create(:id => 8289, :identifier => "aptsnowflake", :sources => [], :saved_items => [])
Session.create(:id => 8290, :identifier => "nearchip", :sources => [], :saved_items => [])
Session.create(:id => 8291, :identifier => "starbath", :sources => [], :saved_items => [])
Session.create(:id => 8292, :identifier => "sassybreeze", :sources => [], :saved_items => [])
Session.create(:id => 8293, :identifier => "easywillow", :sources => [], :saved_items => [])
Session.create(:id => 1320, :identifier => "aptteacher", :sources => [], :completed_to => Sun, 15 Mar 2015 14:36:33 UTC +00:00, :saved_items => [])
Session.create(:id => 1372, :identifier => "jovialsurf", :sources => ["hacker_news"], :saved_items => [])
Session.create(:id => 1396, :identifier => "resilientstorm", :sources => [], :completed_to => Sun, 15 Mar 2015 14:36:33 UTC +00:00, :saved_items => [])
Session.create(:id => 1347, :identifier => "voguesnowflake", :sources => ["beta_list"], :saved_items => [])
Session.create(:id => 1416, :identifier => "simpletemple", :sources => [], :completed_to => Sun, 15 Mar 2015 14:56:47 UTC +00:00, :saved_items => [])
Session.create(:id => 1421, :identifier => "pluckybranch", :sources => [], :completed_to => Sun, 15 Mar 2015 14:56:47 UTC +00:00, :saved_items => [])
Session.create(:id => 1452, :identifier => "punchybeach", :sources => ["hacker_news", "product_hunt"], :saved_items => [])
Session.create(:id => 1478, :identifier => "promptduck", :sources => ["reddit", "hacker_news", "product_hunt", "arstechnica", "beta_list", "macrumors"], :saved_items => [])
Session.create(:id => 1557, :identifier => "snappyfish", :sources => [], :completed_to => Sun, 15 Mar 2015 15:56:26 UTC +00:00, :saved_items => [])
Session.create(:id => 1824, :identifier => "strongice", :sources => ["qudos"], :saved_items => [])
Session.create(:id => 1822, :identifier => "politeball", :sources => [], :completed_to => Sun, 15 Mar 2015 21:07:10 UTC +00:00, :saved_items => [])
