source 'https://rubygems.org'

gem 'rails', '4.2.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry'
  gem 'better_errors'
  gem 'rails_best_practices'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'shoulda-matchers', '2.8.0'
  gem 'factory_girl_rails'
  # gem 'camcorder'
  gem 'seed_dumper'
end

gem 'nokogiri'
gem 'feedjira'
gem 'pg'
gem 'slim'
gem 'sass-rails'
gem 'httpclient'
gem 'open_uri_redirections'
gem 'gmail'
gem 'random_username'
gem 'gruff'
gem 'cloudinary'
gem 'ruby-trello'
gem 'jaccard'
gem 'rufus-scheduler'
